# Generated by Django 5.2.1 on 2026-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("DEVELOPER", "Desarrollador"),
                    ("DIRECTOR", "Directivo"),
                    ("COORDINATOR", "Coordinador"),
                    ("PROFESSOR", "Profesor"),
                    ("STUDENT", "Estudiante"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
