# Generated by Django 5.2.1 on 2026-05-07 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="professor",
            field=models.ForeignKey(
                limit_choices_to={"role": "PROFESSOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="students",
            field=models.ManyToManyField(
                limit_choices_to={"role": "STUDENT"},
                related_name="enrolled_sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="academic.section",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="academic.subject",
            ),
        ),
    ]
