# Generated by Django 5.2.1 on 2026-05-27 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Asignatura"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Código de Asignatura"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
            },
        ),
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del Salón"),
                ),
                ("capacidad", models.IntegerField(verbose_name="Capacidad de Alumnos")),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ubicación/Pabellón"
                    ),
                ),
            ],
            options={
                "verbose_name": "Salón",
                "verbose_name_plural": "Salones",
            },
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Código/Grupo de Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
            },
        ),
        migrations.RemoveField(
            model_name="classsession",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="classsession",
            name="section",
        ),
        migrations.RemoveField(
            model_name="section",
            name="professor",
        ),
        migrations.RemoveField(
            model_name="section",
            name="students",
        ),
        migrations.RemoveField(
            model_name="section",
            name="subject",
        ),
        migrations.CreateModel(
            name="AsignacionClase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horario_inicio", models.TimeField(verbose_name="Horario de Inicio")),
                ("horario_fin", models.TimeField(verbose_name="Horario de Fin")),
                (
                    "profesor",
                    models.ForeignKey(
                        limit_choices_to={"role": "PROFESSOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_profesor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesor Asignado",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_materia",
                        to="academic.asignatura",
                        verbose_name="Asignatura",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_salon",
                        to="academic.salon",
                        verbose_name="Salón",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_grupo",
                        to="academic.seccion",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Clase",
                "verbose_name_plural": "Asignaciones de Clases",
            },
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Matrícula/Carnet"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="¿Está Activo?"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudiante_perfil",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
            },
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Inscripción"
                    ),
                ),
                (
                    "asignacion_clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_clase",
                        to="academic.asignacionclase",
                        verbose_name="Clase Asignada",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_alumno",
                        to="academic.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
            },
        ),
        migrations.DeleteModel(
            name="Classroom",
        ),
    ]
