# Generated by Django 5.2.1 on 2026-05-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_asignatura_salon_seccion_and_more"),
        ("attendance", "0003_alter_attendancerecord_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClassSession",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.AlterUniqueTogether(
            name="inscripcion",
            unique_together={("estudiante", "asignacion_clase")},
        ),
        migrations.AlterUniqueTogether(
            name="asignacionclase",
            unique_together={("seccion", "salon", "horario_inicio")},
        ),
    ]
