# Generated by Django 5.2.1 on 2026-06-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_delete_classsession_delete_section_delete_subject_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asignacionclase",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="asignacionclase",
            name="dia_semana",
            field=models.CharField(
                choices=[
                    ("LUNES", "Lunes"),
                    ("MARTES", "Martes"),
                    ("MIERCOLES", "Miércoles"),
                    ("JUEVES", "Jueves"),
                    ("VIERNES", "Viernes"),
                    ("SABADO", "Sábado"),
                    ("DOMINGO", "Domingo"),
                ],
                default="LUNES",
                max_length=15,
                verbose_name="Día de la Semana",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asignacionclase",
            unique_together={("seccion", "salon", "dia_semana", "horario_inicio")},
        ),
    ]
