# Generated by Django 5.2.1 on 2026-06-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_alter_asignacionclase_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asignacionclase",
            unique_together={("seccion", "dia_semana", "horario_inicio")},
        ),
    ]
