# Generated by Django 5.2.1 on 2026-05-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_asignatura_salon_seccion_and_more"),
        ("attendance", "0002_initial"),
    ]

    operations = [
        # 1. Eliminar la restricción unique_together antigua
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together=set(),
        ),
        # 2. Eliminar el campo viejo 'session'
        migrations.RemoveField(
            model_name="attendancerecord",
            name="session",
        ),
        # 3. Agregar el nuevo campo 'clase'
        migrations.AddField(
            model_name="attendancerecord",
            name="clase",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_logs",
                to="academic.asignacionclase",
            ),
            preserve_default=False,
        ),
        # 4. Alterar el campo 'student'
        migrations.AlterField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asistencias",
                to="academic.estudiante",
            ),
        ),
        # 5. Aplicar la nueva restricción unique_together
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("student", "clase", "timestamp")},
        ),
    ]
