# Generated by Django 5.2.1 on 2026-05-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_delete_classsession_delete_section_delete_subject_and_more"),
        ("attendance", "0003_alter_attendancerecord_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SesionClase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True, verbose_name="fecha")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_CURSO", "en curso"),
                            ("FINALIZADA", "finalizada"),
                        ],
                        default="EN_CURSO",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "asignacion_clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to="academic.asignacionclase",
                        verbose_name="asignación de clase",
                    ),
                ),
            ],
            options={
                "verbose_name": "sesión de clase",
                "verbose_name_plural": "sesiones de clases",
            },
        ),
    ]
