# Generated by Django 5.2.1 on 2026-05-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_delete_classsession_delete_section_delete_subject_and_more"),
        ("attendance", "0004_sesionclase"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hora_entrada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="hora de entrada"
                    ),
                ),
                (
                    "hora_salida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="hora de salida"
                    ),
                ),
                (
                    "similitud_ia",
                    models.FloatField(
                        blank=True, null=True, verbose_name="similitud ia"
                    ),
                ),
                (
                    "es_fraude",
                    models.BooleanField(default=False, verbose_name="¿es fraude?"),
                ),
                (
                    "captura_fraude",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fraudes/",
                        verbose_name="captura de fraude",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="academic.estudiante",
                        verbose_name="estudiante",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="attendance.sesionclase",
                        verbose_name="sesión",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de asistencia",
                "verbose_name_plural": "registros de asistencia",
                "unique_together": {("sesion", "estudiante")},
            },
        ),
        migrations.DeleteModel(
            name="AttendanceRecord",
        ),
    ]
