# Generated by Django 5.2.1 on 2026-06-11 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_alter_asignacionclase_unique_together"),
        ("attendance", "0005_registroasistencia_delete_attendancerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroasistencia",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("ASISTENCIA_NORMAL", "Asistencia Normal"),
                    ("INTRUSO", "Intruso"),
                    ("OTRA_SECCION", "Otra Sección"),
                    ("SPOOFING", "Spoofing"),
                ],
                default="ASISTENCIA_NORMAL",
                max_length=20,
                verbose_name="tipo de evento",
            ),
        ),
        migrations.AddField(
            model_name="sesionclase",
            name="notas_profesor",
            field=models.TextField(
                blank=True, default="", verbose_name="notas del profesor"
            ),
        ),
        migrations.AlterField(
            model_name="registroasistencia",
            name="estudiante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asistencias",
                to="academic.estudiante",
                verbose_name="estudiante",
            ),
        ),
    ]
