# Generated by Django 5.2.1 on 2026-06-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_registroasistencia_tipo_evento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroasistencia",
            name="ultima_vez_visto",
            field=models.TimeField(
                blank=True, null=True, verbose_name="última vez visto"
            ),
        ),
    ]
