# Generated by Django 5.2.1 on 2026-06-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_registroasistencia_ultima_vez_visto"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroasistencia",
            name="alerta_revisada",
            field=models.BooleanField(default=False, verbose_name="¿alerta revisada?"),
        ),
        migrations.AddField(
            model_name="registroasistencia",
            name="notas_auditoria",
            field=models.TextField(
                blank=True, default="", verbose_name="notas de auditoría"
            ),
        ),
    ]
