# Generated by Django 5.2.1 on 2026-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_registroasistencia_alerta_revisada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroasistencia",
            name="historial_intervalos",
            field=models.JSONField(
                blank=True, default=list, verbose_name="historial de intervalos"
            ),
        ),
    ]
